# Generated by Django 4.1 on 2024-02-25 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['score'], 'verbose_name': 'Оценка', 'verbose_name_plural': 'Оценки'},
        ),
    ]
